name: Deploy a new Helmify image to runtime environment
description: Deploy a new Helmify image to runtime environment

inputs:
  instance:
    required: true
    description: 'The instance to deploy'
  dockerhubUsername:
    required: true
    description: 'The username for Docker Hub'
  dockerhubToken:
    required: true
    description: 'The token for Docker Hub'
  deployHost:
    required: true
    description: 'The host to deploy to'
  deployUsername:
    required: true
    description: 'The username for the deployment'
  deployKey:
    required: true
    description: 'The key for the deployment'
  deployPort:
    required: true
    description: 'The port for the deployment'


runs:
  using: "composite"
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.dockerhubUsername }}
        password: ${{ inputs.dockerhubToken }}
    - name: Push Docker Image
      run:  |
        docker tag helmify/helmify:latest helmify/helmify:${{ github.run_id }}${{ github.run_attempt }} && 
        docker push helmify/helmify:${{ github.run_id }}${{ github.run_attempt }}
      shell: bash
    - name: deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ inputs.deployHost }}
        username: ${{ inputs.deployUsername }}
        key: ${{ inputs.deployKey }}
        port: ${{ inputs.deployPort }}
        script: |
          docker pull helmify/helmify:${{ github.run_id }}${{ github.run_attempt }} &&
          docker tag helmify/helmify:${{ github.run_id }}${{ github.run_attempt }} helmify/helmify:dev && 
          wget -O docker-compose.yml https://raw.githubusercontent.com/helmify/helmify/develop/docker-compose.yml &&
          docker compose up -d --force-recreate --no-deps ${{ inputs.instance }}
