name: run helmify
description: 'Run Helmify'

runs:
  using: "composite"
  steps:
    - name: Start Helmify Docker Container
      shell: bash
      run: |
        docker run -d -p 8080:8080 -p 9090:9090 helmify/helmify:${{ github.run_id }}${{ github.run_attempt }} && \
        until printf "." && curl --silent http://localhost:9090/actuator/health; do sleep 2; done;
