apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "REPLACE_ME.fullname" . }}-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
       {{- include "REPLACE_ME.labels" . | nindent 4 }}
     {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
     {{- end }}
data:
  REMOVE: ME
###@helmify:configmap
