apiVersion: v1
kind: Secret
metadata:
  name: {{ include "REPLACE_ME.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
     {{- include "REPLACE_ME.labels" . | nindent 4 }}
type: Opaque
data:
  REMOVE: ME
###@helmify:secrets
