apiVersion: v1
kind: Service
metadata:
  name: {{ include "REPLACE_ME.fullname" . }}
  labels:
    {{- include "REPLACE_ME.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
###@helmify:healthcheckport
  selector:
    {{- include "REPLACE_ME.selectorLabels" . | nindent 4 }}
