name: Run Tester
description: Run a Test application to test helm charts provided by Helmify

inputs:
  name:
    description: 'The directory & image name & helm release name'
    required: true
  port:
    description: 'The port to forward to'
    required: true
  expect:
    description: 'The expected output of the test'
    required: true
  type:
    description: 'The type of the application (spring|quarkus)'
    required: true
  chartFlavor:
    description: 'The chart flavor to use (helm|bitnami)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Pull  ${{ inputs.name }} Tester
      shell: bash
      run: docker pull helmify/${{ inputs.name }}:latest && docker tag helmify/${{ inputs.name }}:latest docker.io/library/${{ inputs.name }}:0.1.0
    - name: Deploy ${{ inputs.name }} ${{ inputs.chartFlavor }} Tester
      uses: ./.github/actions/deploy-tester
      with:
        name: ${{ inputs.name }}
        chartFlavor: ${{ inputs.chartFlavor }}
    - name: Port Forward ${{ inputs.name }} Tester
      shell: bash
      run: kubectl port-forward svc/${{inputs.name}} ${{inputs.port}}:8080 &
    - name: Ping ${{ inputs.name }} Tester
      id: ping
      shell: bash
      run: mvn test -Dtest=KindPingTest -Durl=http://localhost:${{inputs.port}}/ping -Dexpected=${{inputs.expect}}
    - name: Dump log
      if: always()
      shell: bash
      run: kubectl logs svc/${{inputs.name}}
    - name: Uninstall ${{ inputs.name }} Tester
      shell: bash
      run: helm uninstall ${{ inputs.name }}
