name: Run Tester
description: Run a Test application to test helm charts provided by Helmify

inputs:
  name:
    description: 'The directory & image name & helm release name'
    required: true
  port:
    description: 'The port to forward to'
    required: true
  expect:
    description: 'The expected output of the test'
    required: true
  type:
    description: 'The type of the application (spring|quarkus)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Build  ${{ inputs.name }} Tester
      if: ${{ inputs.type  == 'spring' }}
      shell: bash
      run: |
        mvn -B clean compile spring-boot:build-image -Dspring-boot.build-image.imageName=${{ inputs.name }}:0.1.0  --file testing/${{ inputs.name }}/pom.xml
    - name: Build  ${{ inputs.name }} Tester
      if: ${{ inputs.type  == 'quarkus' }}
      shell: bash
      run: |
        mvn clean compile quarkus:image-build -Dquarkus.container-image.name=${{ inputs.name }} -Dquarkus.container-image.tag=0.1.0 --file testing/${{ inputs.name }}/pom.xml \
        && docker tag runner/${{ inputs.name }}:0.1.0 ${{ inputs.name }}:0.1.0
    - name: Deploy ${{ inputs.name }} Tester
      uses: ./.github/actions/deploy-tester
      with:
          name: ${{ inputs.name }}
          chartFlavor: "helm"
    - name: Port Forward ${{ inputs.name }} Tester
      shell: bash
      run: kubectl port-forward svc/${{inputs.name}} ${{inputs.port}}:8080 &
    - name: Ping ${{ inputs.name }} Tester
      shell: bash
      run: mvn test -Dtest=KindPingTest -Durl=http://localhost:${{inputs.port}}/ping -Dexpected=${{inputs.expect}}
    - name: Uninstall ${{ inputs.name }} Tester
      shell: bash
      run: helm uninstall ${{ inputs.name }}
    - name: Deploy ${{ inputs.name }} Tester
      uses: ./.github/actions/deploy-tester
      with:
        name: ${{ inputs.name }}
        chartFlavor: "helm"
    - name: Port Forward ${{ inputs.name }} Tester
      shell: bash
      run: kubectl port-forward svc/${{inputs.name}} ${{inputs.port}}:8080 &
    - name: Ping ${{ inputs.name }} Tester
      shell: bash
      run: mvn test -Dtest=KindPingTest -Durl=http://localhost:${{inputs.port}}/ping -Dexpected=${{inputs.expect}}
    - name: Uninstall ${{ inputs.name }} Tester
      shell: bash
      run: helm uninstall ${{ inputs.name }}
    - name: Deploy ${{ inputs.name }} Tester with Bitnami Chart
      uses: ./.github/actions/deploy-tester
      with:
        name: ${{ inputs.name }}
        chartFlavor: "bitnami"
    - name: Port Forward ${{ inputs.name }} Tester
      shell: bash
      run: kubectl port-forward svc/${{inputs.name}} ${{inputs.port}}:8080 &
    - name: Ping ${{ inputs.name }} Tester
      shell: bash
      run: mvn test -Dtest=KindPingTest -Durl=http://localhost:${{inputs.port}}/ping -Dexpected=${{inputs.expect}}
    - name: Uninstall ${{ inputs.name }} Tester
      shell: bash
      run: helm uninstall ${{ inputs.name }}
