name: Helmify-Testing Mariadb/Elasticsearch/Cassandra/Couchbase

on:
  workflow_call:
  push:
    branches: [ "main", "develop", "feature/**", "fix/**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: 'testing'
          repository: 'helmify/testing'
          clean: "false"
      - name: Set up
        uses: ./.github/actions/setup
        with:
          dockerHubUsername: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerHubToken: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Mariadb/Elasticsearch/Cassandra/Couchbase Testers
        uses: ./.github/actions/build
        with:
          name: mecc

