name: Helmify-Testing Neo4j/Mysql/Mongodb/Kafka

on:
  workflow_call:
  push:
    branches: [ "main", "develop", "feature/**", "fix/**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up
        uses: ./.github/actions/setup
        with:
          dockerHubUsername: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerHubToken: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Neo4j/Mysql/Mongodb/Kafka Testers
        uses: ./.github/actions/build
        with:
          name: nmmk

