name: Helmify E2E Testing

on:
  schedule:
    - cron: '30 5 * * *'
  pull_request:
    branches: [ "main"]
  push:
    branches: [ "develop" ]


jobs:
  e2e-test-helmify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'helmify/testing'
      - uses: helmify/testing/.github/workflows/e2e-test-mariadb-elastic-cassandra-couchbase.yml@main
      - uses: helmify/testing/.github/workflows/e2e-test-neo4j-mysql-mongodb-kafka.yml@main
      - uses: helmify/testing/.github/workflows/e2e-test-postgres-rabbit-redis.yml@main
