name: Helmify E2E Testing

on:
  schedule:
    - cron: '30 5 * * *'
  pull_request:
    branches: [ "main"]
  push:
    branches: [ "develop" ]


jobs:
  e2e-test-mariadb-elastic-cassandra-couchbase:
    uses: helmify/testing/.github/workflows/e2e-test-mariadb-elastic-cassandra-couchbase.yml@main
  e2e-test-neo4j-mysql-mongodb-kafka:
    uses: helmify/testing/.github/workflows/e2e-test-neo4j-mysql-mongodb-kafka.yml@main
  e2e-test-postgres-rabbit-redis:
    uses: helmify/testing/.github/workflows/e2e-test-postgres-rabbit-redis.yml@main
