name: Helmify E2E Testing

on:
  schedule:
    - cron: '30 5 * * *'
  pull_request:
    branches: [ "main"]
  push:
    branches: [ "develop" ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'helmify/testing'
          directory: 'testing'
      - name: test
        uses: ./testing/.github/workflows/e2e-test-postgres-rabbit-redis
