name: Helmify E2E Testing

on:
  schedule:
    - cron: '30 5 * * *'
  pull_request:
    branches: [ "main", "feature/bitnami-charts" ]

jobs:

  e2e-spring-postgres:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-tester
      - name: Run Spring Postgres Tester
        uses: ./.github/actions/run-tester
        with:
          name: spring-postgres-tester
          type: spring
          port: 18000
          expect: postgres

  e2e-quarkus-postgres:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-tester
      - name: Run Quarkus Postgres Tester
        uses: ./.github/actions/run-tester
        with:
          name: quarkus-postgres-tester
          type: quarkus
          port: 18001
          expect: postgres
